spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-orders
              uri: lb://MS-ORDERS
              predicates:
                - Path=/ms-orders/**
              filters:
                - StripPrefix=1

            - id: ms-payments
              uri: lb://MS-PAYMENTS
              predicates:
                - Path=/ms-payments/**
              filters:
                - StripPrefix=1

server:
  port: 8082


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

management:
  endpoints:
    web:
      exposure:
        include: gateway,health

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.boot.autoconfigure: DEBUG