spring:
  application:
    name: ms-payments

  profiles:
    active: ${PROFILE_ACTIVE:dev}

server:
  port: 0

# Config Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka

  instance:
    instance-id: ${spring.application.name}:${random.int}


# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      updateOrder:
        sliding-window-size: 3
        minimum-number-of-calls: 2
        wait-duration-in-open-state: 50s